---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: true

- name: Add Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release
      }} stable"
    filename: docker
    state: present
    update_cache: true

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Install Docker SDK for Python via apt
  apt:
    name:
      - python3-docker
      - python3-dockerpty
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

- name: Configure Docker daemon
  copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "{{ docker_log_max_size | default('10m') }}",
          "max-file": "{{ docker_log_max_file | default('3') }}"
        },
        "storage-driver": "overlay2"
      }
    dest: /etc/docker/daemon.json
    mode: "0644"
  notify: restart docker

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ docker_network }}"
