---
ansible_host: 192.168.1.138

zfs_pools:
  - name: typhoeus
    vdevs:
      - type: raidz2
        disks:
          - "wwn-0x5000c50094184c0b"
          - "wwn-0x5000c500941833e3"
          - "wwn-0x5000c50094186427"
          - "wwn-0x5000c50094184b97"
          - "wwn-0x5000c5009418340b"
      - type: raidz2
        disks:
          - "wwn-0x5000c50094184edb"
          - "wwn-0x5000c500941e6bd3"
          - "wwn-0x5000c50094185aaf"
          - "wwn-0x5000c500941856bb"
          - "wwn-0x5000c50094184097"
      - role: spare
        disks:
          - "wwn-0x5000c5009418429f"
          - "wwn-0x5000c500941e703f"
    filesystem_properties:
      compression: lz4
    pool_properties:
      autoexpand: "on"
  - name: hermes
    vdevs:
      - type: raidz2
        disks:
          - "nvme-INTEL_SSDPE2ME012T4_CVMD5162007Z1P2HGN"
          - "nvme-INTEL_SSDPE2ME012T4_CVMD516400721P2HGN"
          - "nvme-INTEL_SSDPE2ME012T4_CVMD5162003Z1P2HGN"
          - "nvme-INTEL_SSDPE2ME012T4_CVMD5130003S1P2HGN"
    filesystem_properties:
      compression: lz4
      atime: "off"
      recordsize: 8k
    pool_properties:
      autoexpand: "on"

zfs_datasets:
  typhoeus/proxmox_iso:
    properties:
      mountpoint: /typhoeus/proxmox_iso
      compression: lz4
  typhoeus/proxmox_templates:
    properties:
      mountpoint: /typhoeus/proxmox_templates
      compression: lz4

proxmox_storage:
  zfs_iso:
    id: zfs-iso
    type: dir
    path: /typhoeus/proxmox_iso
    content: iso
  zfs_templates:
    id: zfs-templates
    type: dir
    path: /typhoeus/proxmox_templates
    content: vztmpl,images
  hermes:
    id: hermes
    type: zfspool
    pool: hermes
    content: rootdir,images
