- name: Configure ZFS storage pools
  hosts: pve
  become: yes
  gather_facts: yes

  tasks:
    - name: Create mirror ZFS pools
      shell: >
        zpool create {{ item.value.name }}
        {% for mirror_pair in item.value.devices %}
        mirror {{ mirror_pair | join(' ') }}
        {% endfor %}
        {% if item.value.spares is defined %}
        spare {{ item.value.spares | join(' ') }}
        {% endif %}
      args:
        creates: "/{{ item.value.name }}"
      when: item.value.type == "mirror"
      loop: "{{ zfs_pools | dict2items }}"
      loop_control:
        label: "{{ item.value.name }}"

    - name: Create raidz ZFS pools
      shell: >
        zpool create {{ item.value.name }}
        {{ item.value.type }} {{ item.value.devices | join(' ') }}
        {% if item.value.spares is defined %}
        spare {{ item.value.spares | join(' ') }}
        {% endif %}
      args:
        creates: "/{{ item.value.name }}"
      when: item.value.type in ["raidz1", "raidz2", "raidz3"]
      loop: "{{ zfs_pools | dict2items }}"
      loop_control:
        label: "{{ item.value.name }}"

    - name: Set ZFS compression on pools
      shell: zfs set compression={{ item.value.compression | default('lz4') }} {{ item.value.name }}
      args:
        creates: "/{{ item.value.name }}/.zfs"
      loop: "{{ zfs_pools | dict2items }}"
      loop_control:
        label: "{{ item.value.name }}"

    - name: Display ZFS pool status
      shell: zpool status
      register: zpool_status
      changed_when: false

    - name: Show ZFS pools
      debug:
        var: zpool_status.stdout_lines
